### ISSUE TITLE
The help, about,facebook options are not working in pahera web page

### ISSUE THREAD

**Issue by csanthosh** [thebachchaoproject/i-rode#2] opened 2014-11-07 14:15 UTC
Steps to reproduce the bug 

1. Launch the application from grid view
2. Tap on the about option 
3. Assign the necessary link for the “about” option
       (Do the same for   help, follow, twitter, Facebook options)
4. Refresh the link
5. Tap on the about or help or follow options in the application home page

1. Actual result: when user click on the about, help, follow, twitter, Facebook such options in the all pahera web pages those are not working.

2. Expected result:

when user click on the about, help, follow, twitter, Facebook  such options in the pehera web page, it should go for the that screen page.

**Comment by chinmayisk** [comment] 2015-03-14 21:14
invalid bug since this talks about pahera not irode and unclear steps to reproduce hence closing

**Closed by chinmayisk** 2015-03-14 21:14 UTC
